GET http://localhost:5000/api/apis

### Set API key variable for testing
@apiKey = apk.03d8dc3350164117.m9v9hpca.7cd77895

### Basic GET request through the gateway
GET http://localhost:5000/gateway/devchi/humor/random
X-API-KEY: {{apiKey}}

### GET request with query parameters
GET http://localhost:5000/gateway/weather-api/forecast?location=London&days=5
X-API-KEY: {{apiKey}}

### POST request through the gateway
POST https://app.devchihub.com/gateway/url-shortener/api/shorten
Content-Type: application/json
X-API-KEY: apk.df949d6bd7a54231.mab9utg5.d5702eb5

{
  "originalUrl": "https://portal.devchihub.com/docs/url-shortener"
}

### PUT request through the gateway
POST https://app.devchihub.com/gateway/contact-us/contact-us
Content-Type: application/json

{
  "fullName": "John Doe",
  "email": "john@example.com",
  "phone": "070123456789",
  "subject": "Project Inquiry",
  "message": "I'd like to discuss a potential project.",
  "sendTo": "devchijay@gmail.com"
}